spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: SPRING_BATCH
    password: SPRING_BATCH

  sql:
    init:
      schema-locations: classpath:/org/springframework/batch/core/schema-h2.sql
  data:
    mongodb:
      database: spring-batch
      uri: mongodb://localhost:27020/

